import Link from "next/link";

export default function PrivacyPolicy() {
  return (
    <div className="min-h-dvh min-h-screen bg-blood-950 text-white">
      <div className="max-w-2xl mx-auto px-4 py-8 sm:py-12 space-y-8">
        <Link href="/" className="text-sm text-white/40 hover:text-white/60 transition-colors">
          ← Back to Foreplay Frenzy
        </Link>

        <h1 className="text-2xl sm:text-3xl font-bold">Privacy Policy</h1>
        <p className="text-xs text-white/30">Last updated: July 2026</p>

        <div className="space-y-6 text-sm text-white/70 leading-relaxed">
          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-white">1. Overview</h2>
            <p>
              Foreplay Frenzy is designed with privacy in mind. This policy explains how we handle
              (and more importantly, don&apos;t handle) your data.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-white">2. No Data Collection</h2>
            <p>
              We do <strong className="text-white">not</strong> collect, store, transmit, or share any
              personal data. There are no analytics services, no tracking cookies, no third-party
              data processors, and no servers that receive your information.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-white">3. Local Storage Only</h2>
            <p>
              All data generated by the App (game sessions, player profiles, settings, custom card
              packs, achievements) is stored entirely on your device using browser local storage.
              This data never leaves your device.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-white">4. No Accounts</h2>
            <p>
              The App does not require account creation, email addresses, or any form of
              authentication. There is no user registration process.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-white">5. No Internet Communication</h2>
            <p>
              Once loaded, the App can function entirely offline via the service worker cache.
              The App makes no network requests to external servers during normal use.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-white">6. Data Deletion</h2>
            <p>
              You can delete all App data at any time using the &quot;Clear All Data&quot; option in Settings.
              This permanently removes all local storage entries associated with the App.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-white">7. Children&apos;s Privacy</h2>
            <p>
              The App is not intended for users under 18. We do not knowingly collect information
              from anyone. Since we collect no data at all, there is no risk of children&apos;s data
              being processed.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-white">8. Changes to This Policy</h2>
            <p>
              If this privacy policy changes, the updated version will be posted on this page with a
              new &quot;Last updated&quot; date. Given our zero-data-collection approach, changes are
              unlikely to affect your privacy.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-white">9. Contact</h2>
            <p>
              If you have questions about this privacy policy, please open an issue at{" "}
              <a
                href="https://github.com/SondreWiger/foreplay-frenzy/issues"
                target="_blank"
                rel="noopener noreferrer"
                className="underline hover:text-white"
              >
                GitHub
              </a>
              .
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
